### ISSUE TITLE
Cant use parser.stored_definition() 

### ISSUE THREAD

**Issue by DrCesar** [teverett/antlr4-cpp-example#1]
Hi, i am working on a project of a compiler in cpp for Decaf. I have al ready generated the lexer an parser based on decaf grammar, i was using your hello.cpp for a guide but couldn't use the parser.stored_definition().

Everything else is working ok.

**Comment by teverett** [comment]
What's the problem?

**Comment by DrCesar** [comment]
My parser doens't have the method stored_definition()

**Comment by teverett** [comment]
can i see the grammar file?

**Comment by DrCesar** [comment]
Yeah, sorry for asking for a miracle. Hahaha how could you know whats wrong if you dont know the code.
This is a project for a course of my university an i want to use cpp and antlr for the back end and electron and angular for the front end. But i'm starting so thank you for your help.

This is the git where is my project.
https://github.com/DrCesar/Compiler
Feel free of checking everything. Recommendations are welcome.

**Comment by teverett** [comment]
change stored_definition() to program()

**Comment by DrCesar** [comment]
Ok, thanks for the info. Why do i have to change it? Did they change it in a new release?

**Comment by teverett** [comment]
No, it's the name of the first rule.  Your first rule is "program: " so that's what you use.

**Comment by DrCesar** [comment]
Sorry, im having a trouble with the libraries location. I think its because i didnt build the antlr rutime, because i dont know how.
![adf](https://user-images.githubusercontent.com/15188770/35191438-1c313d20-fe40-11e7-8829-65b728752b0b.PNG)
