### ISSUE TITLE
hello.cpp:(.text+0x7c): undefined reference to `antlr4::ANTLRInputStream::ANTLRInputStream(std::istream&)'

### ISSUE THREAD

**Issue by chenhy05** [teverett/antlr4-cpp-example#2]
Hi, I clone this example in my machine (ubuntu16.04), and meet lots of undefined reference problems when linking all .o .a files together (in step $(CC) $(LDARGS) $(OUTPUT)/hello.o $(OUTPUT)/modelicaBaseListener.o $(OUTPUT)/modelicaLexer.o $(OUTPUT)/modelicaListener.o $(OUTPUT)/modelicaParser.o $(LIBS) -o hello).
`hello.cpp:(.text+0x7c): undefined reference to antlr4::ANTLRInputStream::ANTLRInputStream(std::istream&)
hello.cpp:(.text+0xb2): undefined reference to antlr4::CommonTokenStream::CommonTokenStream(antlr4::TokenSource*)
hello.cpp:(.text+0xc1): undefined reference to antlr4::BufferedTokenStream::fill()
hello.cpp:(.text+0xda): undefined reference to antlr4::BufferedTokenStream::getTokens()
output/hello.o: In function antlr4::ANTLRInputStream::~ANTLRInputStream():
hello.cpp:(.text._ZN6antlr416ANTLRInputStreamD2Ev[_ZN6antlr416ANTLRInputStreamD5Ev]+0xd): undefined reference to vtable for antlr4::ANTLRInputStream
hello.cpp:(.text._ZN6antlr416ANTLRInputStreamD2Ev[_ZN6antlr416ANTLRInputStreamD5Ev]+0x40): undefined reference to antlr4::CharStream::~CharStream()'`

However, my classmate is able to make successfully in her macOS.
Any compiler or system requirement to make this hello example ?

**Comment by chenhy05** [comment]
solved!

**Comment by panda-wayback** [comment]
How is it solved

**Comment by panda-wayback** [comment]
> 解决了！
How is it solved

**Comment by panda-wayback** [comment]
> How is it solved

How is it solved
